### ISSUE TITLE
Navbar links overlapping

### ISSUE THREAD

**Issue by Just-ng** [NinjaSpect/ninjaspect.github.io#15]
![Ninja Spect - Google Chrome 13-May-21 2_40_46 PM](https://user-images.githubusercontent.com/83496546/118094740-52a97d00-b3f9-11eb-8faa-c3c7f4124c82.png)

**Comment by samuraininja360** [comment]
Oh ok that just needs media selectors but I have no idea how the middle part overlapped

**Comment by Just-ng** [comment]
> Oh ok that just needs media selectors but I have no idea how the middle part overlapped

Do you mean the Fun Learning part?

**Comment by samuraininja360** [comment]
Yeah the fun learning and the other stuff

**Comment by Ijont-the-developer** [comment]
Lol, is this issue gonna ever get resolved?

**Comment by Just-ng** [comment]
> Lol, is this issue gonna ever get resolved?

I made a PR 'bout that, hasn't been merged yet

**Comment by Ijont-the-developer** [comment]
Im sorry Just-ng if you read this. Its not gonna get resolved

**Comment by BlazerYoo** [comment]
Added responsiveness to the site. Check out https://github.com/BlazerYoo/ninjaspect-site or the fork https://github.com/NinjaSpect/ninjaspect-site.

**Comment by Just-ng** [comment]
Wot
