### ISSUE TITLE
We Need to Work on Educational Games

### ISSUE THREAD

**Issue by samuraininja360** [NinjaSpect/ninjaspect.github.io#26]
**Educational Games**

Use `JavaScript` to program games on websites with personalised experience.

**Comment by Ijont-the-developer** [comment]
Yeah, we can definitely do that. I can do that on scratch. Then use turbo warp to make it fast or download a local HTML to run it and show it on our website. I am suggesting that because my strong suit is scratch. Embed the turbo warp link on the website.

**Comment by Ijont-the-developer** [comment]
uhh, i accidently created a wiki? I don't know what I did
